#!/usr/bin/env bash
#Add new localhost entry
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

#Remove existing facebook.com entries
sudo sed -i '/facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
