#!/usr/bin/env bash
# Supprime l'ancienne entrée localhost (127.0.0.1)
sed -i '/127.0.0.1/d' /etc/hosts

# Ajoute la nouvelle entrée localhost (127.0.0.2)
echo "127.0.0.2 localhost" >> /etc/hosts

# Supprime les anciennes entrées facebook.com s'il y en a
sed -i '/facebook.com/d' /etc/hosts

# Ajoute la nouvelle entrée facebook.com
echo "8.8.8.8 facebook.com" >> /etc/hosts
